CREATE TABLE IF NOT EXISTS applicants (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  program VARCHAR(64) NOT NULL,
  gpa DECIMAL(3,2) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'submitted',
  keywords_text TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
